[workspace]
authors = ["Aditya Singh <dr.singhaditya@hotmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "ELIXIR-SCO-spatial-omics"
platforms = ["osx-arm64","osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=1.26.4"
scipy = ">=1.16.1"
pandas = ">=2.3.2"
scikit-learn = ">=1.7.1"
scikit-image = ">=0.25.2"
matplotlib = ">=3.8.4"
seaborn = ">=0.13.2"
statsmodels = ">=0.14.5"
sympy = ">=1.14.0"
xarray = ">=2024.11.0"

datashader = ">=0.18.2"
bokeh = ">=3.7.3"
holoviews = ">=1.21.0"
colorcet = ">=3.1.0"

jupyter = ">=1.1.1"
jupyterlab = ">=4.4.7"
notebook = ">=7.4.5"
ipykernel = ">=6.30.1,<7"
ipywidgets = ">=8.1.7"

h5py = ">=3.14.0"
zarr = ">=2.18.7"
netcdf4 = ">=1.7.2"
anndata = ">=0.12.0"
mudata = ">=0.3.1"
ome-zarr = ">=0.10.2"
rasterio = ">=1.4.3"
geopandas = ">=1.1.1"
pyogrio = ">=0.11.0"
pyproj = ">=3.7.2"
shapely = ">=2.1.1"
polars-lts-cpu = ">=1.33.0"

dask = ">=2024.11.2"
distributed = ">=2024.11.2"
joblib = ">=1.5.2"

pytorch = ">=2.7.1"
torchvision = ">=0.22.0"
torchaudio = ">=2.8.0"
lightning = ">=2.5.4"
lightning-utilities = ">=0.15.2"
tensorstore = ">=0.1.65"

scanpy = ">=1.11.4"
scvi-tools = ">=1.3.3"
squidpy = ">=1.6.5"

igraph = ">=0.10.16"
python-igraph = ">=0.11.9"
leidenalg = ">=0.10.2"
libleidenalg = ">=0.11.1"
umap-learn = ">=0.5.9.post2"
pynndescent = ">=0.5.13"

tqdm = ">=4.67.1"
psutil = ">=7.0.0"
cloudpickle = ">=3.1.1"
fsspec = ">=2025.9.0"
s3fs = ">=2025.9.0"
gdown = ">=5.2.0"
session-info = ">=1.0.0"
rich = ">=14.1.0"

matplotlib-scalebar = ">=0.9.0"
statannot = ">=0.2.3"

widgetsnbextension = ">=4.0.14"
cellpose = ">=4.0.6,<5"
scip = ">=9.2.3,<10"

[pypi-dependencies]
jax = ">=0.6.2"
jaxlib = ">=0.6.2"
flax = ">=0.10.2"
optax = ">=0.2.5"
orbax-checkpoint = ">=0.8.0"
ml-dtypes = ">=0.5.1"
ml-collections = ">=1.0.0"
numpyro = ">=0.19.0"

torchgmm = ">=0.1.3"
sainsc = ">=0.3.1"
xarray-dataclasses = "<=1.9.1"
xarray-datatree = ">=0.0.14"
xarray-schema = ">=0.0.3"
xarray-spatial = ">=0.4.0"
cellcharter = ">=0.3.5"
spatialdata = ">=0.5.0"
spatialdata-plot = ">=0.2.11, <0.3"
napari-spatialdata = ">=0.5.7, <0.6"
spatialdata-io = ">=0.3.0, <0.4"
liana = ">=1.5.1, <2"
